### ISSUE TITLE
Additional information in 1.2 Install required

### ISSUE THREAD

**Issue by pschoerg** [MyTooliT/ICOc#35]
Please, insert some additional information on how to fulfill the following action:

>>
Before you use the software you need to install it (in developer mode). To do that please run the following command in the root of the repository:
pip install -e .
<<

Something like:
1) Go to the folder, in which you have cloned the repository. You can find the folder by opening a windows explorer and ... (e.g., searching for ICOc)
2) In the ICOc folder open a command shell by ...
3) Insert "pip install -e ." in the command shell and press enter

Pictures would be very helpful. Thank you! Greets, Paul

**Comment by sanssecours** [comment]
Thank you for the bug report. I hope commit https://github.com/MyTooliT/ICOc/commit/d39149aee3bca8c1df1632acf7218e9719ac5a92 fixes the issue. You can see the latest version of the install instructions [here](https://mytoolit.github.io/ICOc/#install).

If you think the install instructions should be improved further, please feel free to reopen this issue.
